### ISSUE TITLE
Choppy output

### ISSUE THREAD

**Issue by le0nard0** [googlemaps/streetsphere#3]
Hi there,

Might be the wrong spot to mention this, I pulled a photosphere I made with my nexus 5 and uploaded it. Everything went fine except the output was choppy. 

I will try to redo it and upload it to my site for you to look at. Is there a way I can optimize my image? The sample photosphere worked perfect.

**Comment by broady** [comment]
In what way was the output choppy?

**Comment by le0nard0** [comment]
Hey sorry, I found a WP Plugin that let me do this so I moved on. 

But it was slow to load when I was panning around. Basically the example image was smooth when I tried it. However when I used my own photosphere the out put was "choppy" not that the image was choppy but it didn't pan smoothly.

**Comment by broady** [comment]
OK, not an issue for here.

https://code.google.com/p/gmaps-api-issues/issues/entry?template=Maps%20API%20v3%20-%20Bug
