### ISSUE TITLE
Panorama not loading, whole browser starts to hang

### ISSUE THREAD

**Issue by code-inflation** [googlemaps/streetsphere#5]
When I generate a photosphere with the suggested picture and then open the downloaded streetview.html file, the panorama does not load and the whole browser starts to hang.  
I tested this on the demo page (https://street-sphere.appspot.com/) using Chrome Version 49.0.2623.87 and Windows 10. It seems to work when using Firefox or Internet Explorer.

**Comment by broady** [comment]
Can you upload the image file? You can send it to me privately (e-mail on GitHub profile) if it's sensitive.
